#!/bin/bash

set -e

IMAGE_NAME="latex-compiler"
TIMEOUT=60

# Run pdflatex inside container with podman's timeout
exec podman run --rm \
  --timeout $TIMEOUT \
  -v "$(pwd)":/latex \
  -w /latex \
  "$IMAGE_NAME" \
  pdflatex "$@"
